### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by zi41531** [pangdahua/php7-wxwork-finance-sdk#1]
安装不成功，报无效指针

**Comment by pangdahua** [comment]
有截图没？

**Comment by zi41531** [comment]
![企业微信截图_20200515100208](https://user-images.githubusercontent.com/1452596/82003644-74abda80-9693-11ea-90b1-8ed334ed7f93.jpg)
![企业微信截图_20200515100255](https://user-images.githubusercontent.com/1452596/82003659-7aa1bb80-9693-11ea-9606-6424411ff474.jpg)

**Comment by zi41531** [comment]
![image](https://user-images.githubusercontent.com/1452596/82003699-92793f80-9693-11ea-8aad-64260a9dfc0e.png)

**Comment by zi41531** [comment]
![image](https://user-images.githubusercontent.com/1452596/82003829-f3a11300-9693-11ea-8237-fa75dfa3aebb.png)
![image](https://user-images.githubusercontent.com/1452596/82003878-13383b80-9694-11ea-8ded-2784cbe82e21.png)

**Comment by pangdahua** [comment]
加我下麻花疼号: 5687046.
我在 ubuntu 14.04 php 7.0 => 7.2 下是可以的
