### ISSUE TITLE
downloadMedia

### ISSUE THREAD

**Issue by along1z1** [pangdahua/php7-wxwork-finance-sdk#10]
[voice] => Array
   (
  [md5sum] => 4ed970e4d640b495e740bad968aed5c9
  [voice_size] => 1266
  [play_length] => 2
  [sdkfileid] => CpsBKjAqWGpub1lmM3RsaWVUN0N6TTZBSTVmZS9ITTVGN1VNQU1jaTlES29GVnVMWldzdTltK251WklhbUFCcjYrZldyVGlReExaSXhNOVl2T3pKWlAwMWQ3MWV1NjlYaGpPYzJ2bTRWeUkzMzMxRkYwWWxlZzBrb3lDb1k4M1VZK0NDMGJxMWtleUpPTllQT3NCUUIzWVIzbUR3PT0SNE5EZGZOemc0TVRNd016TXpOakEwTWpjNU1GODVNemsyTmpnNU9WOHhOVGsxTXpJeU9ERTIaIDc5N2E2Nzc2NzI2NzcwNzQ2ZTc2NjE2ZjczNzc2Yzc4
  )
  
```
$sdkFileId = $xxx['voice']['sdkfileid'];

$obj->downloadMedia($sdkFileId, "/tmp/download");

//返回string(4) "Open"  int(0)
```

麻烦再问一下，这是什么原因，是因为我用体验版，下载不了吗

**Comment by along1z1** [comment]
1

**Comment by tongxin3267** [comment]
你的解决没有 @along1z1

**Comment by along1z1** [comment]
> 你的解决没有 @along1z1

解决了，这个问题是保存的路径不对引起的，路径+文件名

**Comment by wzzphp** [comment]
大佬 怎么获取到$sdkfileid的,解密没成功
