### ISSUE TITLE
大佬,我本地php7.4装上后报错

### ISSUE THREAD

**Issue by baojun123** [pangdahua/php7-wxwork-finance-sdk#13]
我使用php7.1版本安装没有问题，但是使用php7.4版本安装上之后，php -m报错，
![image](https://user-images.githubusercontent.com/16567925/93574077-89dea000-f9ca-11ea-9ad7-ecd1deb6088f.png)

**Comment by pangdahua** [comment]
是不是用的宝塔环境？ 
建议自己编译下php。

**Comment by pangdahua** [comment]
这个问题暂时定位到字符集转换导致的memory leak。

**Comment by pangdahua** [comment]
readme 增加对此问题解决方案
