### ISSUE TITLE
同时给多家企业拉取的时候，在php中new sdk class，结果返回是上一个实例的会话存档拉取结果

### ISSUE THREAD

**Issue by liuzimu1995** [pangdahua/php7-wxwork-finance-sdk#14]
1.        $obj1 = new WxworkFinanceSdkUtil($corpId1,  $secret1, [
            "proxy_host" => "",
        "proxy_password" => "",
            "timeout" => 30,
        ]);

 $obj2 = new WxworkFinanceSdkUtil($corpId2,  $secret2, [
            "proxy_host" => "",
        "proxy_password" => "",
            "timeout" => 30,
        ]);

 $obj2 ->getChatData($seq, 1); // 这里获取到的是obj1企业的数据

ps: sdk版本升级无效，
![image](https://user-images.githubusercontent.com/17780568/94355287-8b3c5680-00b5-11eb-9325-6cadf64e2c85.png)
新老版本均有
（感谢大佬）

**Comment by pangdahua** [comment]
建议使用多进程模型。每个企业独立的进程。
如果可以+下我的麻花疼号 5687046 。我这里没有多余的企业账号

**Comment by pangdahua** [comment]
已修复
