### ISSUE TITLE
编译的时候一直报cannot find WeWorkFinanceSdk_C.h in path

### ISSUE THREAD

**Issue by RayPeng08** [pangdahua/php7-wxwork-finance-sdk#16]
./configure一直报错
WeWorkFinanceSdk_C.h这个文件从官方的SDK拷贝的,也是报这个错误
不知道怎么回事,大佬麻烦指教一下~

**Comment by pangdahua** [comment]
看下文档。
  $INSATLL_PATH_PATH/bin/phpize
        
       ./configure --with-php-config=$INSTALL_PHP_PATH/php-config --with-wxwork-finance-sdk=$WXWORK_FINANCE_C_SDK_PATH
       
        make && make install
WXWORK_FINANCE_C_SDK_PATH 表示的 C_SDK的目录地址

**Comment by RayPeng08** [comment]
> 看下文档。
> $INSATLL_PATH_PATH/bin/phpize
> 
> ```
>    ./configure --with-php-config=$INSTALL_PHP_PATH/php-config --with-wxwork-finance-sdk=$WXWORK_FINANCE_C_SDK_PATH
>    
>     make && make install
> ```
> 
> WXWORK_FINANCE_C_SDK_PATH 表示的 C_SDK的目录地址

谢谢回复,我不知道你说的这个C_SDK的目录地址是什么,我把下载下来的文件放在home里,按照你说的,加入目录后,执行一直提示cannot find WeWorkFinanceSdk_C.h in path /home/wxwork-finance/
不知道什么情况

**Comment by pangdahua** [comment]
C_SDK 是企业微信提供的linux包

**Comment by RayPeng08** [comment]
> C_SDK 是企业微信提供的linux包

哦,谢谢,原来是我一直搞错了,拿了windows的c源码在编译

**Comment by miaoyp** [comment]
@pangdahua 我也遇到这个问题，WeWorkFinanceSdk_C.h 这个是在哪里下载的啊

**Comment by miaoyp** [comment]
@pangdahua 

> C_SDK 是企业微信提供的linux包

这个在哪儿下载啊，找了半天没找到
