### ISSUE TITLE
安装扩展失败？

### ISSUE THREAD

**Issue by zhangweijiang** [pangdahua/php7-wxwork-finance-sdk#2]
请问$INSATLL_PATH_PATH/这个是指php的安装路径?$WXWORK_FINANCE_C_SDK_PATH这个是指你这个项目在服务器上的安装路径还是需要下载企业微信会话存档sdk的c语言版的路径？

**Comment by pangdahua** [comment]
先了解下如何安装php扩展。

依赖企业微信的C语言sdk

./configure --with-php-config=/usr/local/php-7.2/bin/php-config --with-wxwork-finance-sdk=/usr/local/wxwork/C_SDK

**Comment by zhangweijiang** [comment]
好的，解决了，多谢

**Comment by zhangweijiang** [comment]
很不错，若能够支持windows下开发就更好了

**Comment by duruigangduruigang** [comment]
./configure --with-php-config=/www/server/php/73/bin/php-config --with-wxwork-finance-sdk=/www/wwwroot/php7-wxwork-finance-sdk/
执行上面那个，报错下面这个
checking /www/wwwroot/php7-wxwork-finance-sdk/... configure: error: cannot find WeWorkFinanceSdk_C.h in path /www/wwwroot/php7-wxwork-finance-sdk/

怎么回事呢

**Comment by duruigangduruigang** [comment]
已解决多谢

**Comment by duruigangduruigang** [comment]
宝塔环境php7.3

[root@iZ2zeaw7yt2qgbk9syln3hZ php7-wxwork-finance-sdk]# php wxwork_finance_sdk.php 
free(): invalid pointer
已放弃 (核心已转储)

**Comment by pangdahua** [comment]
// 私钥地址
$privateKey = file_get_contents('private.pem');

private.pem 改为存在的地址。
--------------------
貌似file_get_contents 读取不存在的文件引起的段错误, 逻辑我抽时间优化下

**Comment by pangdahua** [comment]
master 已修复

**Comment by Mercis** [comment]
> 已解决多谢
我也报错，你下载了这个文件吗？WeWorkFinanceSdk_C.h

**Comment by xmmao** [comment]
centos8  lnmp7.1  安装报错这个free(): invalid pointer   咋解决呢? 怎么重新编译拓展

**Comment by xmmao** [comment]
> 宝塔环境php7.3
> 
> [root@iZ2zeaw7yt2qgbk9syln3hZ php7-wxwork-finance-sdk]# php wxwork_finance_sdk.php
> free(): invalid pointer
> 已放弃 (核心已转储)

我现在也差不多想放弃了 这个问题到底咋解决啊 我虚拟机上是centos7的时候没问题 但是服务器上是centos8 就出现这个错误 怎么都搞不好
