### ISSUE TITLE
在项目中使用报错

### ISSUE THREAD

**Issue by clark6564** [pangdahua/php7-wxwork-finance-sdk#21]
您好，我这边扩展安装好了，还需要在代码中如何配置？我直接用你写的demo，会直接报错：致命错误: Class 'app\admin\controller\WxworkFinanceSdk' not found。

**Comment by pangdahua** [comment]
额。
new \ WxworkFinanceSdk();
基础还是要打好

**Comment by clark6564** [comment]
谢谢！
