### ISSUE TITLE
sdk问题

### ISSUE THREAD

**Issue by Cathaya1** [pangdahua/php7-wxwork-finance-sdk#22]
大佬，我的sdk已经按照文档对接完成，企业微信也有返回，传参都没有问题的，chatdata返回的是空数组，不知道怎么回事

**Comment by pangdahua** [comment]
企业微信 会话存档需要指定的账号。确认下你的账号和是否存在聊天数据

**Comment by Cathaya1** [comment]
这个问题解决了，下载会话存档素材的时候，调用downloadMedia的报错，
![image](https://user-images.githubusercontent.com/34740398/97669123-65441080-1abe-11eb-83ec-49f2851cd371.png)

**Comment by pangdahua** [comment]
downloadMedia 第二个参数是自定义地址 
downloadMedia($sdkFileid, "/tmp/a.mp3")
