### ISSUE TITLE
WxworkFinanceSdk无法调用

### ISSUE THREAD

**Issue by tomtailer** [pangdahua/php7-wxwork-finance-sdk#25]
现在服务框架为tp5
已执行完phpize && configure && make && make install.
![image](https://user-images.githubusercontent.com/51317031/100960975-55579a80-355c-11eb-858d-4d74b1575251.png)
无错误
调用时无WxworkFinanceSdk方法

**Comment by pangdahua** [comment]
了解下 php如何装扩展。
看下文档 我描述了 需要 wxwork_*.ini 怎么处理
