### ISSUE TITLE
大佬，downloadMedia的时候出现GetMediaData error

### ISSUE THREAD

**Issue by tomtailer** [pangdahua/php7-wxwork-finance-sdk#26]
![image](https://user-images.githubusercontent.com/51317031/101614228-a9281f00-3a47-11eb-955e-6a66568b21c7.png)
打印出来的sdkfileid 是存在值的。请问预计是什么原因导致？应该如何解决
指导一下的。谢谢

**Comment by pangdahua** [comment]
获取下异常返回的code码
