### ISSUE TITLE
centos8，PHP7.4.4安装完成之后报错

### ISSUE THREAD

**Issue by lucas-xsl** [pangdahua/php7-wxwork-finance-sdk#3]
腾讯未提供PHP的JSSDK，非常感谢您开发这个PHP应用，但我在安装的过程中遇到了一些问题：
1、我的环境：Centos8，PHP版本7.4.4
2、使用企业微信提供的SDK版本，1.0和1.1,2版都尝试过，可以成功编译出来.co文件，当从php.ini中引入时，我执行php -m，查看扩展时以下错误，同时用PHP代码也测试了，跑不通；
#php -m
`free(): invalid pointer
Aborted (core dumped)
`

**Comment by duruigangduruigang** [comment]
你这个是弄错了，文件弄错了

**Comment by pangdahua** [comment]
@lucas-xsl 截图贴下 用的是master分支么？
把执行的所以命令都贴一下
