### ISSUE TITLE
CentOS Linux release 8.2.2004 (Core) error： free(): invalid pointer 已放弃 (核心已转储)

### ISSUE THREAD

**Issue by vgocoder** [pangdahua/php7-wxwork-finance-sdk#30]
OS：CentOS Linux release 8.2.2004 (Core) 
Build success

# php -m
free(): invalid pointer
已放弃 (核心已转储)

**Comment by pangdahua** [comment]
#28

**Comment by vgocoder** [comment]
> #28

OS：CentOS Linux release 7.9

works fine on CentOS 7.9
