### ISSUE TITLE
安装完后，重启php报错，请问怎么解决

### ISSUE THREAD

**Issue by guojianrong** [pangdahua/php7-wxwork-finance-sdk#31]
07-May-2021 17:06:30] NOTICE: PHP message: PHP Warning: PHP Startup: Unable to load dynamic library 'C_sdk/libWeWorkFinanceSdk_C.so' (tried: C_sdk/libWeWorkFinanceSdk_C.so (C_sdk/libWeWorkFinanceSdk_C.so: cannot open shared object file: No such file or directory), /www/server/php/73/lib/php/extensions/no-debug-non-zts-20180731/C_sdk/libWeWorkFinanceSdk_C.so.so (/www/server/php/73/lib/php/extensions/no-debug-non-zts-20180731/C_sdk/libWeWorkFinanceSdk_C.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by pangdahua** [comment]
你加载的C_SDK 地址不对

**Comment by guojianrong** [comment]
> 你加载的C_SDK 地址不对

已解决，谢谢

**Comment by oauthq** [comment]
你好，怎么解决的呢。
