### ISSUE TITLE
php7.4 安装完后报错

### ISSUE THREAD

**Issue by Funny-dot** [pangdahua/php7-wxwork-finance-sdk#32]
free(): invalid pointer
/etc/init.d/php-fpm-74: line 53: 12152 Aborted (core dumped) $php_fpm_BIN --daemonize $php_opts

**Comment by pangdahua** [comment]
#28 
先看文档

**Comment by Funny-dot** [comment]
已解决

**Comment by ouyang-max** [comment]
怎么解决的
