### ISSUE TITLE
请问一下PHP Warning:  PHP Startup: wxwork_finance_sdk: Unable to initialize module，怎么解决啊，php74

### ISSUE THREAD

**Issue by WhiteSnowGirl** [pangdahua/php7-wxwork-finance-sdk#33]
`[root@localhost php7-wxwork-finance-sdk]# php -v`
`PHP Warning:  PHP Startup: wxwork_finance_sdk: Unable to initialize module
Module compiled with module API=20180731
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0
PHP 7.4.22 (cli) (built: Aug 10 2021 11:46:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies`

**Comment by WhiteSnowGirl** [comment]
![image](https://user-images.githubusercontent.com/12612585/128816115-028ae05d-56bc-46e5-96da-fa3f7cd7baec.png)

**Comment by WhiteSnowGirl** [comment]
似乎是PHP73可以安装，但是PHP74似乎不兼容你的插件。大佬

**Comment by WhiteSnowGirl** [comment]
重新装一遍，删除掉php7-wxwork-finance-sdk 这个目录下载，就行

**Comment by pangdahua** [comment]
大佬 7.4下木有问题
