### ISSUE TITLE
php8.0 安装后警告

### ISSUE THREAD

**Issue by NanQi** [pangdahua/php7-wxwork-finance-sdk#37]
Warning: Missing arginfo for confirm_wxwork_finance_sdk_compiled() in Unknown on line 0

Warning: Missing arginfo for WxworkFinanceSdk::__construct() in Unknown on line 0

Warning: Missing arginfo for WxworkFinanceSdk::getChatData() in Unknown on line 0

Warning: Missing arginfo for WxworkFinanceSdk::decryptData() in Unknown on line 0

Warning: Missing arginfo for WxworkFinanceSdk::downloadMedia() in Unknown on line 0

Warning: Missing arginfo for WxworkFinanceSdk::getMediaData() in Unknown on line 0

**Comment by williamxviii** [comment]
碰到同样的问题，暂时回退到php7.4。

**Comment by suktec** [comment]
8.0都不行，那8.1更没戏咯

**Comment by pangdahua** [comment]
已支持。感谢@ singee77 的 pr
