### ISSUE TITLE
执行./configure后报错

### ISSUE THREAD

**Issue by kellyfsr** [pangdahua/php7-wxwork-finance-sdk#4]
WeWorkFinanceSdk_C.h文件已经放到这个目录下/opt/php/lib/php/extensions/debug-zts-20180731/

执行 [root@localhost wxwork-sdk]# ./configure --with-php-config=/opt/php/bin/php-config --with-wxwork-finance-sdk=/opt/php/lib/php/extensions/debug-zts-20180731
就报 cannot find WeWorkFinanceSdk_C.h in path /opt/php/lib/php/extensions/debug-zts-20180731
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /opt/php
checking for PHP includes... -I/opt/php/include/php -I/opt/php/include/php/main -I/opt/php/include/php/TSRM -I/opt/php/include/php/Zend -I/opt/php/include/php/ext -I/opt/php/include/php/ext/date/lib
checking for PHP extension directory... /opt/php/lib/php/extensions/debug-zts-20180731
checking for PHP installed headers prefix... /opt/php/include/php
checking if debug is enabled... yes
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... gawk
checking for wxwork_finance_sdk support... yes, shared
checking /opt/php/lib/php/extensions/debug-zts-20180731... configure: error: cannot find WeWorkFinanceSdk_C.h in path /opt/php/lib/php/extensions/debug-zts-20180731

**Comment by pangdahua** [comment]
./configure --with-php-config=/opt/php/bin/php-config --with-wxwork-finance-sdk=企业微信c sdk的路径

路径类似 20160111/C_SDK/

**Comment by pangdahua** [comment]
还有 企业微信的包不要拆开 放到一个目录里

**Comment by kellyfsr** [comment]
可以了，非常感谢
