### ISSUE TITLE
有时候会报access token missing

### ISSUE THREAD

**Issue by CreationLee** [pangdahua/php7-wxwork-finance-sdk#40]
问题：有时候会报access token missing，持续一小时左右，然后就会自己恢复。
排查步骤：

1. secret跟corp id填写没问题
2. 使用的laravels(swoole)，常驻进程拉取，维护的全局单例，不存在频繁初始化sdk的现象

困扰了很久了，使用多种其它方案重写，但是都没解决

**Comment by pangdahua** [comment]
是跑一段时间后然后报错么？
企微的financesdk是哪个版本的？

**Comment by CreationLee** [comment]
> 是跑一段时间后然后报错么？ 企微的financesdk是哪个版本的？

是的，跑一段就会报错，持续一小时左右，然后跑一段又继续。
sdk是最新版本的，这是老版本sdk的bug？

**Comment by pangdahua** [comment]
拉取一个企业的还是多个企业的？

**Comment by CreationLee** [comment]
> 拉取一个企业的还是多个企业的？

一个企业的

**Comment by pangdahua** [comment]
https://wiki.swoole.com/wiki/page/p-strace.html
因为还没遇到过类似情况。能否根据这个文档跟下

**Comment by pangdahua** [comment]
有个mochat 的版本，没见到有反馈类似问题

https://wiki.swoole.com/wiki/page/p-strace.html
能够使用上述文档 在发生问题的时候跟下请求

**Comment by CreationLee** [comment]
> https://wiki.swoole.com/wiki/page/p-strace.html 因为还没遇到过类似情况。能否根据这个文档跟下

好的，感谢

**Comment by CreationLee** [comment]
> 有个mochat 的版本，没见到有反馈类似问题
> 
> https://wiki.swoole.com/wiki/page/p-strace.html 能够使用上述文档 在发生问题的时候跟下请求

对了，还有个情况，起初怀疑跟swoole有关系，就用golang重写了拉取服务，之前的PHP用作备用服务，但是还是出现一样的问题，golang出问题的时候切到PHP，一样的问题

**Comment by CreationLee** [comment]
> 有个mochat 的版本，没见到有反馈类似问题
> 
> https://wiki.swoole.com/wiki/page/p-strace.html 能够使用上述文档 在发生问题的时候跟下请求

你好，大佬，这几天没出状况，但是我也trace了一下，日志如下

**Comment by CreationLee** [comment]
> 有个mochat 的版本，没见到有反馈类似问题
> 
> https://wiki.swoole.com/wiki/page/p-strace.html 能够使用上述文档 在发生问题的时候跟下请求

你好，大佬，这几天没出问题，但是我trace了一下，日志如下

**Comment by CreationLee** [comment]
> 有个mochat 的版本，没见到有反馈类似问题
> 
> https://wiki.swoole.com/wiki/page/p-strace.html 能够使用上述文档 在发生问题的时候跟下请求

你好，大佬，这几天没出问题，但是我trace了一下，日志如下

31026 recvfrom(25, 0x7f9463ffa83f, 1, MSG_PEEK|MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
31026 recvfrom(25, 0x7f94639f3000, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
31026 epoll_ctl(16, EPOLL_CTL_ADD, 25, {EPOLLIN, {u32=38712624, u64=38712624}}) = 0
31026 epoll_wait(16, [{EPOLLIN, {u32=38712624, u64=38712624}}], 4096, 60000) = 1
31026 epoll_ctl(16, EPOLL_CTL_DEL, 25, NULL) = 0

**Comment by pangdahua** [comment]
企微的官方回复:
access_token missing 报错是因为该应用调用 access_token 次数过多，封禁一小时。
在一小时内 允许 15000 次请求。
