### ISSUE TITLE
Unable to load dynamic library 'wxwork_finance_sdk.so

### ISSUE THREAD

**Issue by weavingtan** [pangdahua/php7-wxwork-finance-sdk#41]
已解决，在docker 下基于alpine 是行不通的，缺少必要的组件

**Comment by pangdahua** [comment]
建议把解决方案贴一下。tks

**Comment by 0758jian** [comment]
> 

我尝试在Dockerfile ln依懒包名就行了
ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

**Comment by weavingtan** [comment]
在docker 下基于alpine , 添加`apk add gcompat`，我使用这个方式解决的

**Comment by sxc654** [comment]
老哥, 你用alpine的镜像是内一个, 我现在使用的是php:7.2-fpm-alpine3.12, 调用的时候回出现Segmentation fault问题.
