### ISSUE TITLE
有时会报“Call WeWorkFinanceSdk_t GetChatData error”

### ISSUE THREAD

**Issue by xinghailong** [pangdahua/php7-wxwork-finance-sdk#42]

**Comment by pangdahua** [comment]
上下文补全下，谢谢

**Comment by xinghailong** [comment]
> 上下文补全下，谢谢

正常运行过程中出现的偶发现象。

**Comment by pangdahua** [comment]
try catch 包一下。 $e->getCode() 与企微的错误代码对齐下

**Comment by jeff-getlucky** [comment]
我也每天会遇到
errorMessage:Call WeWorkFinanceSdk_t GetChatData error
errorCode:10001

**Comment by pangdahua** [comment]
搜了下。遇到 10001 问题挺多的。 只能按照官方的建议 重试

**Comment by jeff-getlucky** [comment]
> 搜了下。遇到 10001 问题挺多的。 只能按照官方的建议 重试

谢谢
