### ISSUE TITLE
Swoole环境下数据错乱

### ISSUE THREAD

**Issue by pandasir** [pangdahua/php7-wxwork-finance-sdk#45]
在Swoole环境下  我用两家企业`for`循环实例化`sdk`调用 两家企业的`sdk`是两个实例, 但`getChatData`接口获取的加密消息数据两家企业是错乱的,  想问下是不支持协程环境么？

**Comment by pangdahua** [comment]
使用 swoole process 解决该问题。 底层不支持协程
