### ISSUE TITLE
你好  请问这个是怎么回事 是少了文件嘛 ？

### ISSUE THREAD

**Issue by lee-1127** [pangdahua/php7-wxwork-finance-sdk#6]
checking /var/www/html/php7-wxwork-finance-sdk/... configure: error: cannot find WeWorkFinanceSdk_C.h in path /var/www/html/php7-wxwork-finance-sdk/

**Comment by pangdahua** [comment]
./configure --with-php-config=/opt/php/bin/php-config --with-wxwork-finance-sdk=企业微信c sdk的路径

路径类似 20160111/C_SDK/

**Comment by lee-1127** [comment]
> ./configure --with-php-config=/opt/php/bin/php-config --with-wxwork-finance-sdk=企业微信c sdk的路径
> 
> 路径类似 20160111/C_SDK/

好的，谢谢了
