### ISSUE TITLE
使用插件报错

### ISSUE THREAD

**Issue by along1z1** [pangdahua/php7-wxwork-finance-sdk#8]
array(3) { ["errcode"]=> int(41001) ["errmsg"]=> string(167) "access_token missing, hint: [1595297094_45_a21af24b99541439ee],

**Comment by pangdahua** [comment]
检查下自己的corpid和secret

**Comment by along1z1** [comment]
确实是自己的疏忽，secret填错了

**Comment by along1z1** [comment]
1
